---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt cache on Debian
      ansible.builtin.apt:
        update_cache: true
        name: acl
      when: ansible_os_family == "Debian"
- name: Include main playbook
  ansible.builtin.import_playbook: >-
    ../../playbook-config.yml
  vars:
    domain: local
