---

- name: Setup cfssl container
  tags:
    - cfssl
    - config
  block:
    - name: Create directory for cfssl config
      ansible.builtin.file:
        name: "{{ compose_directory_result.path }}/cfssl/config"
        state: directory
        mode: "0755"
        owner: "{{ compose_user }}"
        group: "{{ compose_user }}"
      register: cfssl_directory_result
    - name: Create cfssl ca.json
      ansible.builtin.copy:
        content: "{{ cfssl_ca | to_nice_json }}"
        dest: "{{ cfssl_directory_result.path }}/ca.json"
        mode: "0644"
        owner: "{{ compose_user }}"
        group: "{{ compose_user }}"
      vars:
        certificate_cn: "{{ domain }}"
    - name: Create cfssl config.json
      ansible.builtin.copy:
        content: "{{ cfssl_config | to_nice_json }}"
        dest: "{{ cfssl_directory_result.path }}/config.json"
        mode: "0644"
        owner: "{{ compose_user }}"
        group: "{{ compose_user }}"
    - name: Template cfssl certificate config files
      ansible.builtin.template:
        src: cfssl-service.json.j2
        dest: "{{ cfssl_directory_result.path }}/{{ service }}.json"
        mode: "0644"
        owner: "{{ compose_user }}"
        group: "{{ compose_user }}"
      vars:
        certificate_cn:
         - "{{ service }}.{{ domain }}"
         - "{% if gitlab.enable_registry %}registry.{{ domain }}{% endif %}"
         - "{% if service == "gitlab" and gitlab.enable_localhost %}localhost{% endif %}"
      loop: "{{ cfssl_services }}"
      loop_control:
        loop_var: service

- name: Check if certificate exists
  ansible.builtin.stat:
    path: "{{ compose_directory_result.path }}/etc/cfssl/ca.pem"
  register: ca_certificate

- name: Generate cfssl ca certificate
  ansible.builtin.command:
    cmd: "docker compose run --rm \
      --entrypoint sh cfssl \
      -c \"cfssl genkey --initca /etc/cfssl/config/ca.json | cfssljson -bare ca\""
  args:
    chdir: "{{ compose_directory_result.path }}"
  when: not ca_certificate.stat.exists
  tags:
    - cfssl
    - config
    - certificates

- name: Generate service certificates
  ansible.builtin.include_tasks: certificates.yml
  tags:
    - cfssl
    - config
    - certificates
  loop: "{{ cfssl_services }}"
  loop_control:
    loop_var: service
